[[education]]
institution = "Carnegie Mellon University"
area = "Information Security"
startDate = "2025-08-18"
studyType = "Master of Science"
url = "https://cmu.edu"
image = "resume/cmu-seal.png"

[[education]]
institution = "University of Massachusetts, Amherst"
area = "Computer Science"
startDate = "2021-09-01"
endDate = "2024-05-17"
score = "3.7 GPA"
studyType = "Bachelor of Science"
url = "https://umass.edu"
image = "resume/umass-seal.png"

[[projects]]
name = "franciscosp.com"
description = "This website, used as a blog and portfolio, uses the Hugo static generator and a custom hand-made theme."
url = "/"

[[projects]]
name = "Simple Processor Simulator for a Custom Architecture"
description = [
    "Processor simulator for a custom architecture designed and implemented as coursework for a Graduate-level course.",
    "A Web port of the simulator, which includes the assembler, is available on this web site. The port and project share the same codebase, the former merely being recompiled to WebAssembly.",
]
startDate = "2024-03-01"
url = "/projects/processor-simulator/about/"

[[certificates]]
name = "CompTIA A+ V14"
acquired = "2025-09-17"
image = "resume/aplus.svg"

[[languages]]
name = "English"
proficiency = "Fluent"

[[languages]]
name = "Spanish"
proficiency = "Conversational"

[[skills]]
category = "Programming and Querying Languages"
entries = [
    "C",
    "C++",
    "C# .NET",
    "Rust",
    "Java",
    "TypeScript",
    "JavaScript",
    "PowerShell",
    "SQL",
]

[[skills]]
category = "Markup Languages"
entries = ["HTML5", "CSS/SASS", "XAML", "TOML", "XML", "JSON", "YAML"]

[[skills]]
category = "Tools"
entries = [
    "Ghidra",
    "WireShark",
    "Node.JS",
    "NuGet",
    "Visual Studio",
    "Git",
    "PostgreSQL",
    "CMake",
]
